name: Black Formatter Check

on: [push, pull_request]

jobs:
  black:
    name: "Black Check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check out source repository
        uses: psf/black@stable
        with:
          options: "--check --verbose --exclude /migrations/"
          src: "./src"
          version: "~= 22.0"