name: Lint Code Base

on: [pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8

      - name: Check Flake8 results
        run: |
          flake8_result=$?
          if [ $flake8_result -ne 0 ]; then
            echo "Flake8 found errors. Commit will be cancelled."
            exit 1
          else
            echo "No Flake8 errors found. Commit will proceed."
          fi
